"""
Combined Overnight Rebound Bot — Unified config re-export.

Live constants:
    INTRADAY_ETF_ALLOCATION_PCT  = 1.00
    MR_ALLOC_PER_POSITION_PCT    = 0.30
    MR_MAX_PRIMARY_POSITIONS     = 3
    MR_MAX_TOTAL_ALLOCATION_PCT  = 0.60  # Base 60% single-stock MR; combined 90%
    MR_ADV_CAP_PCT               = 0.003

All settings live in their dedicated files:
  config_broker.py   — API credentials, endpoints, data feed
  config_runtime.py  — state paths, logging
  config_universe.py — price/ADV filters, presets, lookback periods
  config_strategy.py — sleeve configs, exit rules, timing
"""

# Broker
from bot.config_broker import (          # noqa: F401
    ALPACA_API_KEY, ALPACA_SECRET_KEY, ALPACA_PAPER,
    ALPACA_BASE_URL, ALPACA_DATA_URL, DATA_FEED,
    MASSIVE_API_KEY, MASSIVE_BASE_URL,
)

# Runtime
from bot.config_runtime import (         # noqa: F401
    STATE_DIR, STATE_FILE, LOG_DIR, LOG_FILE, TRADE_LOG_FILE,
    LOG_LEVEL, LOG_FORMAT,
    POSITIONS_FILE, DAILY_LOG_FILE,
)

# Universe
from bot.config_universe import (        # noqa: F401
    UNIVERSE_PRESET, UNIVERSE_PRESETS,
    MIN_PRICE, MAX_PRICE,
    ADV_LOOKBACK_DAYS,
)

# Strategy
from bot.config_strategy import (        # noqa: F401
    # ── LIVE CONSTANTS ──
    INTRADAY_ETF_ALLOCATION_PCT,
    MR_ALLOC_PER_POSITION_PCT, MR_MAX_PRIMARY_POSITIONS,
    MR_MAX_TOTAL_ALLOCATION_PCT, MR_ADV_CAP_PCT,
    # Master switches
    ETF_ROUTER_ENABLED, OVERNIGHT_ETF_ENABLED, MR_OVERNIGHT_ENABLED,
    # Position sizing
    MAX_LEVERAGE, MAX_POSITION_DOLLARS, MIN_SHARES, MIN_POSITION_DOLLARS,
    ADV_DOLLAR_MULTIPLIER, ENABLE_LEFTOVER_REDEPLOYMENT,
    MR_MAX_WATERFALL_POSITIONS,
    # ETF Router symbols + tape
    ETF_ROUTER_SYMBOLS, ETF_TAPE_UPDATE_INTERVAL_SECONDS,
    ETF_ENTRY_MAX_SPREAD_PCT, ETF_ENTRY_MAX_SLIPPAGE_PCT, ETF_ENTRY_MAX_STALE_SECONDS,
    ETF_ENTRY_WARN_STALE_SECONDS,
    # Intraday strategies 1-5 params
    VXX_SPIKE_MIN_RETURN_PCT, VXX_SPIKE_QQQ_RANGE_MIN_PCT, VXX_SPIKE_QQQ_RANGE_MAX_PCT,
    VXX_SPIKE_VEHICLE, VXX_SPIKE_EXIT_TIME,
    VXX_COLLAPSE_VXX_MAX_RETURN_PCT, VXX_COLLAPSE_QQQ_MIN_RETURN_PCT,
    VXX_COLLAPSE_VEHICLE, VXX_COLLAPSE_EXIT_TIME,
    MOMENTUM_QQQ_MIN_RETURN_PCT, MOMENTUM_VEHICLE, MOMENTUM_ANTI_VEHICLE, MOMENTUM_EXIT_TIME,
    MOMENTUM_TAKE_PROFIT_PCT, MOMENTUM_STOP_LOSS_PCT,
    VXX_HIGH_RISK_RETURN_PCT, VXX_HIGH_RISK_PRICE,
    ROUTER_LONG_SPREAD_MIN_PCT, ROUTER_LONG_VEHICLE, ROUTER_LONG_EXIT_TIME,
    ROUTER_LONG_TAKE_PROFIT_PCT, ROUTER_LONG_STOP_LOSS_PCT,
    SVIX_LONG_MIN_RETURN_PCT, SVIX_LONG_VEHICLE, SVIX_LONG_EXIT_TIME,
    SVIX_LONG_TAKE_PROFIT_PCT,
    # Overnight ETF exit timing
    OVERNIGHT_ETF_EXIT_TIME,
    # SL/TP table
    ETF_SL_TP,
    # Single-stock MR sleeve
    MR_MIN_PRICE, MR_MAX_PRICE, MR_DAY_RET_MAX, MR_VOLUME_RATIO_MIN,
    MR_CLOSE_POSITION_MAX, MR_LATE_DROP_MAX,
    MR_RANK_BY_CLOSE_LOCATION_ONLY, MR_MIN_CANDIDATES, MR_MIN_AVG_DOLLAR_VOLUME,
    # Prior-day return filter (free MR pipeline)
    MR_FREE_PRIOR_RET_MIN, MR_FREE_PRIOR_RET_MAX, MR_FREE_PRIOR_RET_REQUIRE_DATA,
    # Execution safety
    ENTRY_BP_BUFFER_PCT, ENTRY_MAX_SPREAD_PCT, ENTRY_MAX_SLIPPAGE_PCT,
    ENTRY_SUBMIT_TIMEOUT_SECONDS, ENTRY_RECONCILE_TIMEOUT_SECONDS, ENTRY_SUBMIT_MAX_WORKERS,
    DAILY_LOSS_LIMIT_PCT,
    # Timing
    DATA_COLLECTION_TIME, SCORING_TIME, ENTRY_TIME, ENTRY_HARD_CUTOFF_TIME,
    MARKET_OPEN_TIME, MORNING_EXIT_TIME, MORNING_FAILSAFE_TIME,
    MORNING_CANCEL_OPEN_ORDERS_TIME,
    BOT_START_TIME, ROUTER_DECISION_TIME, ROUTER_1010_TIME,
    INTRADAY_EXIT_1500, INTRADAY_ETF_HARD_FLATTEN_TIME,
    # MR regime sizing
    ENABLE_MR_ETF_REGIME_SIZING, MR_ETF_REGIME_SYMBOLS,
    MR_ETF_NEGATIVE_SIZE_MULT, MR_ETF_POSITIVE_SIZE_MULT,
    # Intraday MR (morning individual stock sleeve)
    INTRADAY_MR_ENABLED,
    INTRADAY_MR_VIX_THRESHOLD, INTRADAY_MR_GAP_THRESHOLD,
    INTRADAY_MR_MIN_CANDIDATES, INTRADAY_MR_MAX_CANDIDATES,
    INTRADAY_MR_MIN_ADV_DOLLARS, INTRADAY_MR_BUDGET_PCT,
    INTRADAY_MR_UNIVERSE_MIN_PRICE, INTRADAY_MR_UNIVERSE_MAX_PRICE,
    INTRADAY_MR_STAGE1_TIME, INTRADAY_MR_STAGE2_TIME,
    INTRADAY_MR_MAX_ENTRY_DELAY_S, INTRADAY_MR_ENTRY_CUTOFF,
    INTRADAY_MR_MIN_REMAINING_HOLD_S, INTRADAY_MR_HARD_FLATTEN_TIME,
    # Swing ETF sleeve (Portfolio 7)
    SWING_SLEEVE_ENABLED, SWING_SYMBOLS, SWING_THRESHOLD_PCT,
    SWING_NUGT_STREAK_MIN, SWING_HOLD_DAYS, SWING_ALLOCATION_PCT,
    SWING_REGIME_SYMBOL, SWING_REGIME_MA_PERIOD,
)
