"""
Combined Overnight Rebound Bot — Unified config re-export.

Live constants:
    INTRADAY_ETF_ALLOCATION_PCT  = 0.90
    MR_ALLOC_PER_POSITION_PCT    = 0.30
    MR_MAX_PRIMARY_POSITIONS     = 3
    MR_MAX_TOTAL_ALLOCATION_PCT  = 0.90
    MR_ADV_CAP_PCT               = 0.003

All settings live in their dedicated files:
  config_broker.py   — API credentials, endpoints, data feed
  config_runtime.py  — state paths, logging
  config_universe.py — price/ADV filters, presets, lookback periods
  config_strategy.py — sleeve configs, exit rules, timing
"""

# Broker
from bot.config_broker import (          # noqa: F401
    ALPACA_API_KEY, ALPACA_SECRET_KEY, ALPACA_PAPER,
    ALPACA_BASE_URL, ALPACA_DATA_URL, DATA_FEED,
    MASSIVE_API_KEY, MASSIVE_BASE_URL,
)

# Runtime
from bot.config_runtime import (         # noqa: F401
    STATE_DIR, STATE_FILE, LOG_DIR, LOG_FILE, TRADE_LOG_FILE,
    LOG_LEVEL, LOG_FORMAT,
    POSITIONS_FILE, DAILY_LOG_FILE,
)

# Universe
from bot.config_universe import (        # noqa: F401
    UNIVERSE_PRESET, UNIVERSE_PRESETS,
    MIN_PRICE, MAX_PRICE,
    ADV_LOOKBACK_DAYS,
)

# Strategy
from bot.config_strategy import (        # noqa: F401
    # ── LIVE CONSTANTS ──
    INTRADAY_ETF_ALLOCATION_PCT,
    MR_ALLOC_PER_POSITION_PCT, MR_MAX_PRIMARY_POSITIONS,
    MR_MAX_TOTAL_ALLOCATION_PCT, MR_ADV_CAP_PCT,
    # Master switches
    ETF_ROUTER_ENABLED, MR_OVERNIGHT_ENABLED, MR_PERMISSION_MODE,
    # Position sizing
    MAX_LEVERAGE, MAX_POSITION_DOLLARS, MIN_SHARES, MIN_POSITION_DOLLARS,
    ADV_DOLLAR_MULTIPLIER, ENABLE_LEFTOVER_REDEPLOYMENT,
    MR_MAX_WATERFALL_POSITIONS,
    # ETF Router
    ETF_ROUTER_SYMBOLS, ETF_TAPE_UPDATE_INTERVAL_SECONDS,
    ETF_ENTRY_MAX_SPREAD_PCT, ETF_ENTRY_MAX_SLIPPAGE_PCT, ETF_ENTRY_MAX_STALE_SECONDS,
    # MR sleeve
    MR_MIN_PRICE, MR_MAX_PRICE, MR_DAY_RET_MAX, MR_VOLUME_RATIO_MIN,
    MR_CLOSE_POSITION_MAX, MR_LATE_DROP_MAX,
    MR_RANK_BY_CLOSE_LOCATION_ONLY, MR_MIN_CANDIDATES, MR_MIN_AVG_DOLLAR_VOLUME,
    # Execution safety
    ENTRY_BP_BUFFER_PCT, ENTRY_MAX_SPREAD_PCT, ENTRY_MAX_SLIPPAGE_PCT,
    ENTRY_SUBMIT_TIMEOUT_SECONDS, ENTRY_RECONCILE_TIMEOUT_SECONDS, ENTRY_SUBMIT_MAX_WORKERS,
    DAILY_LOSS_LIMIT_PCT,
    # Timing
    DATA_COLLECTION_TIME, SCORING_TIME, ENTRY_TIME, ENTRY_HARD_CUTOFF_TIME,
    MARKET_OPEN_TIME, MORNING_EXIT_TIME, V2_FAILSAFE_TIME,
    MORNING_CANCEL_OPEN_ORDERS_TIME,
    BOT_START_TIME, ROUTER_DECISION_TIME, ROUTER_ENTRY_TIME,
    SQQQ_EXIT_TIME, TQQQ_EXIT_TIME, INTRADAY_ETF_HARD_FLATTEN_TIME,
    # V2 fallback
    ENABLE_V2_FALLBACK, V2_LONG_ENTRY_WINDOW_START, V2_LONG_ENTRY_WINDOW_END,
    V2_SHORT_ENTRY_WINDOW_START, V2_SHORT_ENTRY_WINDOW_END,
    V2_HYBRID_CHECKPOINT_TIME, V2_FINAL_EXIT_TIME, V2_QQQ_RANGE_BREAKOUT_THRESHOLD,
    V2_ALLOWED_SUBTYPES, V2_TRAIL_PCT, V2_LONG_VEHICLE, V2_SHORT_VEHICLE,
    MR_ALLOWED_SUBTYPES,
    # P1 fallback
    ENABLE_P1_FALLBACK, P1_ENTRY_TIME, P1_EXIT_TIME, P1_VEHICLE,
    P1_REQUIRED_SUBTYPE, P1_REQUIRED_XLK_POSITIVE,
    # Early close handling
    SKIP_MR_ON_EARLY_CLOSE, SKIP_INTRADAY_ETF_ON_EARLY_CLOSE,
    # Premarket dynamic limits
    ENABLE_PREMARKET_DYNAMIC_LIMIT_SELLS, PREMARKET_DYNAMIC_START_TIME,
    PREMARKET_DYNAMIC_FINAL_TIME, PREMARKET_DYNAMIC_CHECK_INTERVAL_MINUTES,
    PREMARKET_SIP_DELAY_MINUTES,
    PREMARKET_DYNAMIC_LIMIT_TIME_IN_FORCE,
    PREMARKET_DYNAMIC_LIMIT_EXTENDED_HOURS, PREMARKET_DYNAMIC_MAX_STALE_MINUTES,
    PREMARKET_DYNAMIC_DEFAULT_LIMIT_PCT, PREMARKET_DYNAMIC_SPARSE_HIGH_RETURN_LIMIT_PCT,
    PREMARKET_DYNAMIC_VERY_HIGH_RETURN_NO_CAP_PCT, PREMARKET_DYNAMIC_HIGH_RETURN_NO_CAP_PCT,
    PREMARKET_DYNAMIC_MODERATE_RETURN_PCT,
    # MR regime sizing
    ENABLE_MR_ETF_REGIME_SIZING, MR_ETF_REGIME_SYMBOLS,
    MR_ETF_NEGATIVE_SIZE_MULT, MR_ETF_POSITIVE_SIZE_MULT,
)
