"""
Combined Overnight Rebound Bot — Unified config re-export.

Sleeve 1: MR_WIDE (Mean Reversion)
  - Buy 15:50, $1–5, day_ret <= -3%, vol_ratio >= 1.5x
  - Exit 09:30

Sleeve 2: GDP_BASE / MOM_CLEAN (Green-Day Pullback)
  - Buy 15:50, $1–10, day_ret +1% to +10%, below VWAP
  - Exit 09:30

All settings live in their dedicated files:
  config_broker.py   — API credentials, endpoints, data feed
  config_runtime.py  — state paths, logging
  config_universe.py — price/ADV filters, presets, lookback periods
  config_strategy.py — sleeve configs, exit rules, timing

This file re-exports everything so that existing code using
``from bot import config; config.X`` continues to work.
"""

# Broker
from bot.config_broker import (          # noqa: F401
    ALPACA_API_KEY, ALPACA_SECRET_KEY, ALPACA_PAPER,
    ALPACA_BASE_URL, ALPACA_DATA_URL, DATA_FEED,
    MASSIVE_API_KEY, MASSIVE_BASE_URL,
)

# Runtime
from bot.config_runtime import (         # noqa: F401
    STATE_DIR, STATE_FILE, LOG_DIR, LOG_FILE, TRADE_LOG_FILE,
    LOG_LEVEL, LOG_FORMAT,
    POSITIONS_FILE, DAILY_LOG_FILE,
)

# Universe
from bot.config_universe import (        # noqa: F401
    UNIVERSE_PRESET, UNIVERSE_PRESETS,
    MIN_PRICE, MAX_PRICE,
    ADV_LOOKBACK_DAYS,
)

# Strategy
from bot.config_strategy import (        # noqa: F401
    # Combined sleeve mode
    ENABLE_COMBINED_SLEEVES,
    MR_ALLOCATION_PCT, GDP_ALLOCATION_PCT, COMBINED_MAX_POSITIONS,
    MR_WEIGHT, MOM_WEIGHT,
    # Position sizing
    MAX_LEVERAGE, ADV_CAP_PCT, MAX_POSITION_DOLLARS, MIN_SHARES,
    MAX_SINGLE_POSITION_PCT, MIN_POSITION_DOLLARS,
    # MR sleeve
    MR_MIN_PRICE, MR_MAX_PRICE, MR_DAY_RET_MAX, MR_VOLUME_RATIO_MIN,
    MR_CLOSE_POSITION_MAX, MR_LATE_DROP_MAX, MR_MAX_POSITIONS,
    # GDP sleeve
    GDP_MIN_PRICE, GDP_MAX_PRICE, GDP_DAY_RET_MIN, GDP_DAY_RET_MAX,
    GDP_REQUIRE_BELOW_VWAP, GDP_LATE_MOM_MAX, GDP_MAX_CLOSE_POSITION, GDP_MAX_POSITIONS,
    # Execution safety
    ENTRY_BP_BUFFER_PCT,
    DAILY_LOSS_LIMIT_PCT,
    # Timing
    DATA_COLLECTION_TIME, SCORING_TIME, ENTRY_TIME,
    MARKET_OPEN_TIME, GDP_EXIT_TIME, MR_EXIT_TIME, V2_FAILSAFE_TIME,
    MORNING_CANCEL_OPEN_ORDERS_TIME,
    ENABLE_PREMARKET_DYNAMIC_LIMIT_SELLS, PREMARKET_DYNAMIC_START_TIME,
    PREMARKET_DYNAMIC_FINAL_TIME, PREMARKET_DYNAMIC_CHECK_INTERVAL_MINUTES,
    PREMARKET_DYNAMIC_DATA_FEED, PREMARKET_DYNAMIC_LIMIT_TIME_IN_FORCE,
    PREMARKET_DYNAMIC_LIMIT_EXTENDED_HOURS, PREMARKET_DYNAMIC_MAX_STALE_MINUTES,
    PREMARKET_DYNAMIC_DEFAULT_LIMIT_PCT, PREMARKET_DYNAMIC_SPARSE_HIGH_RETURN_LIMIT_PCT,
    PREMARKET_DYNAMIC_VERY_HIGH_RETURN_NO_CAP_PCT, PREMARKET_DYNAMIC_HIGH_RETURN_NO_CAP_PCT,
    PREMARKET_DYNAMIC_MODERATE_RETURN_PCT,
    USE_SIP_SNAPSHOT_PREMARKET_BACKUP, SIP_SNAPSHOT_MAX_SPREAD_PCT,
    SIP_IEX_CONFIRM_DIFF_PCT, SIP_ALLOW_HIGH_CORRECTION,
    PREMARKET_DYNAMIC_NO_DATA_FALLBACK_LIMIT_PCT,
    ENABLE_FAST_OPEN_MARKET_EXIT,
    ENABLE_RED_OPEN_TRAIL_EXIT, RED_OPEN_TRAIL_PCT,
    RED_OPEN_TRAIL_FAILSAFE_TIME, RED_OPEN_TRAIL_PRICE_BUFFER_PCT,
)

